---
- name: Verify correct leader ip
  debug: var=groups['cribl-leader'][0]

- name: Create cribl user
  ansible.builtin.user:
    name: cribl-edge
    comment: Cribl Edge Account User
    password: '*'
    create_home: false

- name: Change the working directory to /tmp before executing the command
  ansible.builtin.shell: curl -Lso - $(curl https://cdn.cribl.io/dl/latest-x64) | tar zxv
  args:
    chdir: /tmp

- name: Move cribl from /tmp/cribl to /opt/cribl-edge
  ansible.builtin.shell: rm -rf /opt/cribl-edge
  ignore_errors: yes

- name: Move cribl from /tmp/cribl to /opt/cribl-edge
  ansible.builtin.shell: mv /tmp/cribl /opt/cribl-edge

- name: Recursively change ownership of cribl directory
  ansible.builtin.file:
    path: /opt/cribl-edge
    state: directory
    recurse: yes
    owner: cribl-edge
    group: cribl-edge

- name: Disable Cribl Edge to start at boot time with systemd
  ansible.builtin.shell: /opt/cribl-edge/bin/cribl boot-start disable
  ignore_errors: yes

- name: Bootstrap Edge to leader
  ansible.builtin.shell: /opt/cribl-edge/bin/cribl mode-managed-edge -H {{ groups['cribl-leader'][0] }} -p {{ cribl_edge_port }} -u {{ cribl_auth_token }} -g {{ cribl_group }}
  ignore_errors: yes

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /opt/cribl-edge/local/cribl/auth/certs
    state: directory
    mode: '0755'

- name: Add certs to server
  ansible.builtin.copy:
    src: "{{ CUSTOM_DIR_ROLES }}/cribl-edge/files/demo-cert.crt"
    dest: /opt/cribl-edge/local/cribl/auth/certs/demo-cert.crt
    mode: '0644'

- name: Add keys to server
  ansible.builtin.copy:
    src: "{{ CUSTOM_DIR_ROLES }}/cribl-edge/files/demo-key.key"
    dest: /opt/cribl-edge/local/cribl/auth/certs/demo-key.key
    mode: '0644'

- name: Add/update certificate name in certificates.yml
  ansible.builtin.copy:
    src: "{{ CUSTOM_DIR_ROLES }}/cribl-edge/files/certificates.yml"
    dest: /opt/cribl-edge/local/cribl/certificates.yml
    mode: '0644'

- name: Template a file to instance.yml
  ansible.builtin.template:
    src: "{{ CUSTOM_DIR_ROLES }}/cribl-edge/files/instance.yml.j2"
    dest: /opt/cribl-edge/local/_system/instance.yml
    mode: '0644'

- name: Recursively change ownership of cribl directory
  ansible.builtin.shell: chown -R cribl-edge:cribl-edge /opt/cribl-edge/

- name: Enable Cribl Edge to start at boot time with systemd
  ansible.builtin.shell: /opt/cribl-edge/bin/cribl boot-start enable -m systemd -u cribl-edge

- name: Restart cribl service - Edge
  ansible.builtin.systemd:
    name: cribl-edge.service
    state: restarted