---
- name: Get stats of a file
  ansible.builtin.stat:
    path: /usr/share/keyrings/elasticsearch-keyring.gpg
  register: st

- name: Download and install the Public Signing Key
  ansible.builtin.shell: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg
  when: st.stat.islnk is not defined

- name: Save the repository definition to /etc/apt/sources.list.d/elastic-8.x.list
  ansible.builtin.shell: echo "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main" | sudo tee /etc/apt/sources.list.d/elastic-8.x.list
  when: st.stat.islnk is not defined

- name: Run apt-get update and install elasticsearch
  ansible.builtin.shell: sudo apt-get install apt-transport-https

- name: Run apt-get update and install elasticsearch
  ansible.builtin.shell: sudo apt-get update && sudo apt-get install elasticsearch

# - name: Update apt cache and make sure elasticsearch is installed
#   ansible.builtin.apt:
#     name: elasticsearch
#     update_cache: yes

- name: Copy elasticsearch.yml to /etc/elasticsearch
  ansible.builtin.template:
    src: "{{ CUSTOM_DIR_ROLES }}/elasticsearch/files/elasticsearch.yml.j2"
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: root
    mode: '0644'

- name: Enable service elasticsearch
  ansible.builtin.systemd:
    name: elasticsearch.service
    enabled: true

- name: Make sure a service unit is running
  ansible.builtin.systemd:
    state: started
    name: elasticsearch.service

- name: Create password file
  ansible.builtin.shell: echo '---' > /etc/elasticsearch/main.yml

- name: Set elasticsearch password
  ansible.builtin.shell: /usr/share/elasticsearch/bin/elasticsearch-reset-password -u elastic -a -b | grep 'New value:' >> /etc/elasticsearch/main.yml

- name: Set elasticsearch password
  ansible.builtin.shell: sed -i 's/New value/elastic_password/g' /etc/elasticsearch/main.yml

- name: Store file into roles/elasticsearch/vars/main.yml
  ansible.builtin.fetch:
    src: /etc/elasticsearch/main.yml
    dest: "{{ CUSTOM_DIR_ROLES }}/elasticsearch/vars/main.yml"
    flat: true

- name: Store copy of elasticsearch http_ca.crt cert in kibana files
  ansible.builtin.fetch:
    src: /etc/elasticsearch/certs/http_ca.crt
    dest: "{{ CUSTOM_DIR_ROLES }}/kibana/files/http_ca.crt"
    flat: true

- name: Delete temporary password file
  ansible.builtin.shell: rm /etc/elasticsearch/main.yml                                                                                                                                                            